# vim: ft=ruby
#source 'http://10.105.64.10/gemrepo'
source 'https://rubygems.org'
# testing
#gem 'atom'
gem 'addressable'
gem 'bson'
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'rest-client'
gem 'chronic'
gem 'cuporter'
gem 'wrong'
gem 'rake'
gem 'poltergeist', '~> 1.4.1'
gem 'active_support'
gem 'selenium-webdriver', '~> 2.34.0'
gem 'json', '~> 1.7.7'
gem 'i18n'
gem 'debugger'
gem 'headless'
gem 'cuke_sniffer'
